version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - .:/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
